name: example
description: Example app for dart_melty_soundfont
version: 1.0.0

environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  raw_sound: ^0.3.0+1
  dart_melty_soundfont:
    path: ../

assets: 
  - assets/TimGM6mb_but_fixed__piano_.sf2