name: example
description: Example app for dart_melty_soundfont
version: 1.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_pcm_sound: ^1.2.2
  dart_melty_soundfont:
    path: ../

flutter:
  assets: 
    - assets/TimGM6mbEdit.sf2